### ISSUE TITLE
RxQ 2 roadmap

### ISSUE THREAD

**Issue by skokenes** [axisgroup/RxQ#47]
- [x] add session level event streams
- [x] delta mode
- [x] add esm export to support tree shaking
- [x] upgrade to rxjs 6
- [x] session close method? refactor session as a sync value?
- [x] new utility operators
- [x] add ability to access suspend Subject from session instance
- [x] update docs and examples

**Comment by skokenes** [comment]
separated dist packages for CJS, ESM5, ESM2015. tree shaking now working with webpack 4. 
https://github.com/axisgroup/RxQ/tree/bundling

**Comment by skokenes** [comment]
session level event streams done in v1.1.0 branch https://github.com/axisgroup/RxQ/tree/v1.1.0

**Comment by skokenes** [comment]
delta mode now in branch v1.1.0 https://github.com/axisgroup/RxQ/tree/v1.1.0

**Comment by skokenes** [comment]
done and published :)
